//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Olivetti
{
    using System;
    using System.Collections.Generic;
    
    public partial class CARHAR
    {
        public System.DateTime CARHARTAR { get; set; }
        public int CARHARREFNO { get; set; }
        public int CARHARTIPI { get; set; }
        public int CARHARKAYONC { get; set; }
        public int CARHAROZELFIS { get; set; }
        public int CARHARKAYNAK { get; set; }
        public int CARHARKARREFNO { get; set; }
        public int CARHARMUHREFNO { get; set; }
        public string CARHARCARKOD { get; set; }
        public string CARHARCARUNVAN { get; set; }
        public string CARHARCARKARSIKOD { get; set; }
        public string CARHARCARKARSIUNVAN { get; set; }
        public int CARHARSIRANO { get; set; }
        public int CARHARISTIPNO { get; set; }
        public string CARHARISTIPKOD { get; set; }
        public string CARHAREVRAKNO { get; set; }
        public string CARHARACIKLAMA { get; set; }
        public int CARHARGCFLAG { get; set; }
        public decimal CARHARTUTAR { get; set; }
        public string CARHARDOVKOD { get; set; }
        public string CARHARDOVTUR { get; set; }
        public decimal CARHARDOVTUTAR { get; set; }
        public System.DateTime CARHARVADETAR { get; set; }
        public System.DateTime CARHARVALORTAR { get; set; }
        public string CARHAROZKOD { get; set; }
        public int CARHARCSKENDI { get; set; }
        public int CARHARODENDI { get; set; }
        public string CARHARACIKLAMA1 { get; set; }
        public string CARHARACIKLAMA2 { get; set; }
        public string CARHARACIKLAMA3 { get; set; }
        public string CARHARMUHKOD { get; set; }
        public string CARHARMASMER { get; set; }
        public int CARHARIADEFLAG { get; set; }
        public System.DateTime CARHARKDVVADESI { get; set; }
        public decimal CARHARKDVTUTAR { get; set; }
        public int CARHARTOPREFNO { get; set; }
        public string CARHAREKCHAR1 { get; set; }
        public string CARHAREKCHAR2 { get; set; }
        public int CARHAREKINT1 { get; set; }
        public int CARHAREKINT2 { get; set; }
        public System.DateTime CARHAREKDATE1 { get; set; }
        public System.DateTime CARHAREKDATE2 { get; set; }
        public decimal CARHAREKTUT1 { get; set; }
        public decimal CARHAREKTUT2 { get; set; }
        public decimal CARHAREKMIK1 { get; set; }
        public decimal CARHAREKMIK2 { get; set; }
        public decimal CARHAREKDOVTUT1 { get; set; }
        public decimal CARHAREKDOVTUT2 { get; set; }
        public decimal CARHAREKORAN1 { get; set; }
        public decimal CARHAREKORAN2 { get; set; }
        public string CARHARDOVKOD2 { get; set; }
        public string CARHARDOVTUR2 { get; set; }
        public decimal CARHARDOVTUTAR2 { get; set; }
        public decimal CARHARDOVKUR { get; set; }
        public decimal CARHARDOVKUR2 { get; set; }
        public decimal CARHARODENEN { get; set; }
        public decimal CARHARKALAN { get; set; }
        public int CARHARODEREFNO { get; set; }
        public int CARHARODESIRANO { get; set; }
    }
}
