//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Olivetti
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEPO
    {
        public string DEPKOD { get; set; }
        public string DEPADI { get; set; }
        public string DEPYETKODU { get; set; }
        public string DEPYETADI { get; set; }
        public string DEPADRES1 { get; set; }
        public string DEPADRES2 { get; set; }
        public string DEPADRES3 { get; set; }
        public string DEPTELEFON { get; set; }
        public string DEPACIKLAMA1 { get; set; }
        public string DEPACIKLAMA2 { get; set; }
        public string DEPACIKLAMA3 { get; set; }
        public string DEPACIKLAMA4 { get; set; }
        public string DEPACIKLAMA5 { get; set; }
        public string DEPOZKOD1 { get; set; }
        public string DEPOZKOD2 { get; set; }
        public string DEPOZKOD3 { get; set; }
        public string DEPOZKOD4 { get; set; }
        public string DEPOZKOD5 { get; set; }
        public string DEPOFIYATNO { get; set; }
    }
}
