//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Olivetti
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEPSTKKART
    {
        public string DEPSTKSTKKOD { get; set; }
        public string DEPSTKDEPOKOD { get; set; }
        public string DEPSTKOZKOD1 { get; set; }
        public string DEPSTKOZKOD2 { get; set; }
        public string DEPSTKOZKOD3 { get; set; }
        public string DEPSTKOZKOD4 { get; set; }
        public string DEPSTKOZKOD5 { get; set; }
        public string DEPSTKACIK1 { get; set; }
        public string DEPSTKACIK2 { get; set; }
        public string DEPSTKACIK3 { get; set; }
        public string DEPSTKACIK4 { get; set; }
        public string DEPSTKACIK5 { get; set; }
        public decimal DEPSTKBAKIYE { get; set; }
        public decimal DEPSTKBAKIYE2 { get; set; }
        public decimal DEPSTKBAKIYE3 { get; set; }
        public decimal DEPSTKBAKIYE4 { get; set; }
        public decimal DEPSTKBAKIYE5 { get; set; }
        public decimal DEPSTKYAOFIYAT { get; set; }
        public decimal DEPSTKKRITIKSEVIYE { get; set; }
        public decimal DEPSTKOPTIMALSEVIYE { get; set; }
        public string DEPSTKBOLKODU { get; set; }
        public string DEPSTKREYKODU { get; set; }
        public string DEPSTKRAFKODU { get; set; }
        public int DEPSTKCALFLAG { get; set; }
        public decimal DEPSTKOZELBAKIYE { get; set; }
        public decimal DEPSTKOZELBAKIYE2 { get; set; }
        public decimal DEPSTKOZELBAKIYE3 { get; set; }
        public decimal DEPSTKOZELBAKIYE4 { get; set; }
        public decimal DEPSTKOZELBAKIYE5 { get; set; }
        public decimal DEPSTKREZGIRSIPMIK { get; set; }
        public decimal DEPSTKREZGIRSIPTUT { get; set; }
        public decimal DEPSTKREZCIKSIPMIK { get; set; }
        public decimal DEPSTKREZCIKSIPTUT { get; set; }
        public decimal DEPSTKREZGIRURTMIK { get; set; }
        public decimal DEPSTKREZGIRURTTUT { get; set; }
        public decimal DEPSTKREZCIKURTMIK { get; set; }
        public decimal DEPSTKREZCIKURTTUT { get; set; }
    }
}
