//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Olivetti
{
    using System;
    using System.Collections.Generic;
    
    public partial class FATFISTOPLAM
    {
        public System.DateTime FFTTAR { get; set; }
        public int FFTREFNO { get; set; }
        public int FFTTIPI { get; set; }
        public int FFTGCFLAG { get; set; }
        public int FFTKAYONC { get; set; }
        public int FFTIPTALFLAG { get; set; }
        public int FFTKAYNAK { get; set; }
        public int FFTIADEFLAG { get; set; }
        public int FFTKDVDAHILFLAG { get; set; }
        public string FFTCARKOD { get; set; }
        public string FFTEVRAKNO1 { get; set; }
        public string FFTEVRAKNO2 { get; set; }
        public string FFTEVRAKNO3 { get; set; }
        public int FFTKONU { get; set; }
        public string FFTBASLIK { get; set; }
        public decimal FFTTUTAR { get; set; }
        public int FFTONCELIK { get; set; }
        public string FFTFORMUL { get; set; }
        public decimal FFTMATRAH { get; set; }
        public decimal FFTORAN { get; set; }
        public decimal FFTKDVORAN { get; set; }
        public string FFTDOVKOD { get; set; }
        public string FFTDOVTUR { get; set; }
        public decimal FFTDOVTUTAR { get; set; }
        public System.DateTime FFTVADETAR { get; set; }
        public int FFTTAMSAYI1 { get; set; }
        public int FFTTAMSAYI2 { get; set; }
        public int FFTTAMSAYI3 { get; set; }
        public string FFTKOSUL { get; set; }
        public string FFTACIKLAMA1 { get; set; }
        public decimal FFTSAYI1 { get; set; }
        public int FFTVADESAYI { get; set; }
        public string FFTKARTKOD { get; set; }
        public int FFTEFATFLAG { get; set; }
    }
}
