//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Olivetti
{
    using System;
    using System.Collections.Generic;
    
    public partial class FATFISTIP
    {
        public int FATFTMODUL { get; set; }
        public int FATFTNO { get; set; }
        public string FATFTKOD { get; set; }
        public string FATFTACIKLAMA { get; set; }
        public int FATFTONAY { get; set; }
        public int FATFTEVRAKNO { get; set; }
        public string FATFTDIZDOS { get; set; }
        public string FATFTMUHGRUP { get; set; }
        public int FATFTSTKFTNO { get; set; }
        public int FATFTCARFTNO { get; set; }
        public int FATFTMUHFTNO { get; set; }
        public int FATFTKASFTNO { get; set; }
        public int FATFTBANFTNO { get; set; }
        public int FATFTKDVDAHIL { get; set; }
        public int FATFTKAPALI { get; set; }
        public int FATFTTEVNO { get; set; }
        public int FATFTISLGRPNO { get; set; }
        public string FATFTCARMUHGRUP { get; set; }
        public int FATFTMAXSATIR { get; set; }
        public int FATFTOTVFLAG { get; set; }
        public int FATFTKDVOTVBLOKAJ { get; set; }
        public int FATFTEEVRAKNO { get; set; }
    }
}
