//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Olivetti
{
    using System;
    using System.Collections.Generic;
    
    public partial class FATFIS
    {
        public System.DateTime FATFISTAR { get; set; }
        public int FATFISREFNO { get; set; }
        public int FATFISTIPI { get; set; }
        public int FATFISGCFLAG { get; set; }
        public int FATFISKAYONC { get; set; }
        public int FATFISIPTALFLAG { get; set; }
        public int FATFISKAYNAK { get; set; }
        public int FATFISSTKREFNO { get; set; }
        public int FATFISCARREFNO { get; set; }
        public int FATFISMUHREFNO { get; set; }
        public int FATFISKASREFNO { get; set; }
        public int FATFISBANREFNO { get; set; }
        public int FATFISKAPFLAG { get; set; }
        public int FATFISBASFLAG { get; set; }
        public int FATFISOZELFIS { get; set; }
        public int FATFISDEPOFLAG { get; set; }
        public int FATFISIADEFLAG { get; set; }
        public int FATFISKDVDAHILFLAG { get; set; }
        public int FATFISTEVKIFATFLAG { get; set; }
        public string FATFISANADEPO { get; set; }
        public string FATFISPARTIKOD { get; set; }
        public string FATFISODEMEKOD { get; set; }
        public string FATFISSATKOD { get; set; }
        public string FATFISMASMER { get; set; }
        public string FATFISCARKOD { get; set; }
        public string FATFISCARUNVAN { get; set; }
        public int FATFISADRESNO { get; set; }
        public string FATFISADRES1 { get; set; }
        public string FATFISADRES2 { get; set; }
        public string FATFISADRES3 { get; set; }
        public string FATFISPOSTAKOD { get; set; }
        public string FATFISULKE { get; set; }
        public string FATFISIL { get; set; }
        public string FATFISILCE { get; set; }
        public string FATFISVERDAIRE { get; set; }
        public string FATFISVERHESNO { get; set; }
        public string FATFISSAAT { get; set; }
        public System.DateTime FATFISVADETAR { get; set; }
        public System.DateTime FATFISKDVVADETAR { get; set; }
        public System.DateTime FATFISIRSTAR { get; set; }
        public string FATFISIRSNO { get; set; }
        public string FATFISEVRAKNO1 { get; set; }
        public string FATFISEVRAKNO2 { get; set; }
        public string FATFISEVRAKNO3 { get; set; }
        public string FATFISOZKOD1 { get; set; }
        public string FATFISOZKOD2 { get; set; }
        public string FATFISOZKOD3 { get; set; }
        public string FATFISACIKLAMA1 { get; set; }
        public string FATFISACIKLAMA2 { get; set; }
        public string FATFISACIKLAMA3 { get; set; }
        public string FATFISHAZKOD { get; set; }
        public System.DateTime FATFISHAZTAR { get; set; }
        public string FATFISHAZNOT { get; set; }
        public string FATFISKONTKOD { get; set; }
        public System.DateTime FATFISKONTTAR { get; set; }
        public string FATFISKONTNOT { get; set; }
        public string FATFISONAYKOD { get; set; }
        public System.DateTime FATFISONAYTAR { get; set; }
        public string FATFISONAYNOT { get; set; }
        public decimal FATFISKDVORANI { get; set; }
        public decimal FATFISMALTOP { get; set; }
        public decimal FATFISKALINDYTOP { get; set; }
        public decimal FATFISKALINDTTOP { get; set; }
        public decimal FATFISSATINDTOP { get; set; }
        public decimal FATFISGENINDTOP { get; set; }
        public decimal FATFISSATMASTOP { get; set; }
        public decimal FATFISGENMASTOP { get; set; }
        public decimal FATFISBRUTTOPLAM { get; set; }
        public decimal FATFISKDVMATRAHI { get; set; }
        public decimal FATFISKDVTUTARI { get; set; }
        public decimal FATFISARATOPLAM { get; set; }
        public decimal FATFISKDVALTIINDTOP { get; set; }
        public decimal FATFISKDVALTIEKTOP { get; set; }
        public decimal FATFISGENTOPLAM { get; set; }
        public decimal FATFISTEVTUTAR { get; set; }
        public System.DateTime FATFISDOVTAR { get; set; }
        public string FATFISDOVKOD { get; set; }
        public string FATFISDOVTUR { get; set; }
        public decimal FATFISDOVKUR { get; set; }
        public decimal FATFISGENDOVTOP { get; set; }
        public int FATFISTEVNO { get; set; }
        public decimal FATFISTEVORAN { get; set; }
        public int FATFISSEVNO { get; set; }
        public string FATFISISYKOD { get; set; }
        public int FATFISOTVFLAG { get; set; }
        public int FATFISOTVKDVBLOKAJ { get; set; }
        public decimal FATFISTOPOTV { get; set; }
        public decimal FATFISTOPOTUT { get; set; }
        public string FATFISTCKIMLIKNO { get; set; }
        public System.DateTime FATFISTRNTAR { get; set; }
        public int FATFISTRNREFNO { get; set; }
        public int FATFISTRNTIPI { get; set; }
        public int FATFISEFATFLAG { get; set; }
        public decimal FATFISEKVERGIINDTOP { get; set; }
        public decimal FATFISEKVERGIILVTOP { get; set; }
        public decimal FATFISEKVERGITOP { get; set; }
    }
}
