//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Olivetti
{
    using System;
    using System.Collections.Generic;
    
    public partial class FATHAR
    {
        public System.DateTime FATHARTAR { get; set; }
        public int FATHARREFNO { get; set; }
        public int FATHARTIPI { get; set; }
        public int FATHARGCFLAG { get; set; }
        public int FATHARKAYONC { get; set; }
        public int FATHARIPTALFLAG { get; set; }
        public int FATHARKAYNAK { get; set; }
        public int FATHARIADE { get; set; }
        public string FATHARCARKOD { get; set; }
        public int FATHARSIRANO { get; set; }
        public int FATHARKODTIP { get; set; }
        public string FATHARSTKKOD { get; set; }
        public string FATHARSTKCINS { get; set; }
        public string FATHARSTKBRM { get; set; }
        public string FATHARDEPOKOD { get; set; }
        public string FATHARBARKOD { get; set; }
        public string FATHAROZDESKOD { get; set; }
        public string FATHARBENZERKOD { get; set; }
        public decimal FATHARMIKTAR { get; set; }
        public decimal FATHARMIKTAR2 { get; set; }
        public decimal FATHARMIKTAR3 { get; set; }
        public decimal FATHARMIKTAR4 { get; set; }
        public decimal FATHARMIKTAR5 { get; set; }
        public string FATHARFIYTIP { get; set; }
        public decimal FATHARFIYAT { get; set; }
        public decimal FATHARTUTAR { get; set; }
        public string FATHARDOVKOD { get; set; }
        public string FATHARDOVTUR { get; set; }
        public decimal FATHARDOVTUTAR { get; set; }
        public string FATHAROZKOD { get; set; }
        public string FATHARACIKLAMA { get; set; }
        public decimal FATHARKDVYUZ { get; set; }
        public decimal FATHARISKYUZ1 { get; set; }
        public decimal FATHARISKYUZ2 { get; set; }
        public decimal FATHARISKYUZ3 { get; set; }
        public decimal FATHARISKYUZ4 { get; set; }
        public decimal FATHARISKYUZ5 { get; set; }
        public decimal FATHARISKYTUT1 { get; set; }
        public decimal FATHARISKYTUT2 { get; set; }
        public decimal FATHARISKYTUT3 { get; set; }
        public decimal FATHARISKYTUT4 { get; set; }
        public decimal FATHARISKYTUT5 { get; set; }
        public decimal FATHARISKGTUT1 { get; set; }
        public decimal FATHARISKGTUT2 { get; set; }
        public decimal FATHARISKGTUT3 { get; set; }
        public decimal FATHARISKGTUT4 { get; set; }
        public decimal FATHARISKGTUT5 { get; set; }
        public decimal FATHARDIGERIND { get; set; }
        public decimal FATHARTOPLAMIND { get; set; }
        public decimal FATHARKDVMATRAH { get; set; }
        public decimal FATHARKDVTUTAR { get; set; }
        public decimal FATHARTOPLAMTUT { get; set; }
        public System.DateTime FATHARVADETAR { get; set; }
        public string FATHARACIKLAMA1 { get; set; }
        public string FATHARACIKLAMA2 { get; set; }
        public string FATHARACIKLAMA3 { get; set; }
        public string FATHARPARTINO { get; set; }
        public string FATHARMASMER { get; set; }
        public string FATHARSERINO1 { get; set; }
        public string FATHARSERINO2 { get; set; }
        public int FATHARRB1 { get; set; }
        public int FATHARRB2 { get; set; }
        public int FATHARRB3 { get; set; }
        public int FATHARRB4 { get; set; }
        public int FATHARRB5 { get; set; }
        public string FATHARSATKOD { get; set; }
        public string FATHARODEMEKOD { get; set; }
        public decimal FATHARTOPLAMMAS { get; set; }
        public decimal FATHARNETTUTAR { get; set; }
        public decimal FATHARNETFIYAT { get; set; }
        public decimal FATHARMALIYET { get; set; }
        public decimal FATHAROTVMATRAH { get; set; }
        public decimal FATHAROTVORAN { get; set; }
        public decimal FATHAROTVFIYAT { get; set; }
        public decimal FATHARTOPOTV { get; set; }
        public decimal FATHAROTVTUTAR { get; set; }
        public string FATHARMUHKOD { get; set; }
        public decimal FATHARMUHYANIND { get; set; }
        public decimal FATHARMUHYANMAS { get; set; }
        public decimal FATHARDOVFIYAT { get; set; }
        public decimal FATHAREBTEN { get; set; }
        public decimal FATHAREBTBOY { get; set; }
        public decimal FATHAREBTYUK { get; set; }
        public decimal FATHAREBTHCM { get; set; }
        public decimal FATHAREBTAGR { get; set; }
        public string FATHAREKCHAR1 { get; set; }
        public string FATHAREKCHAR2 { get; set; }
        public int FATHAREKINT1 { get; set; }
        public int FATHAREKINT2 { get; set; }
        public System.DateTime FATHAREKDATE1 { get; set; }
        public System.DateTime FATHAREKDATE2 { get; set; }
        public decimal FATHAREKTUT1 { get; set; }
        public decimal FATHAREKTUT2 { get; set; }
        public decimal FATHAREKMIK1 { get; set; }
        public decimal FATHAREKMIK2 { get; set; }
        public decimal FATHAREKDOVTUT1 { get; set; }
        public decimal FATHAREKDOVTUT2 { get; set; }
        public decimal FATHAREKORAN1 { get; set; }
        public decimal FATHAREKORAN2 { get; set; }
        public decimal FATHARDOVKUR { get; set; }
        public int FATHAREFATFLAG { get; set; }
        public string FATHAROTVVERKOD { get; set; }
        public string FATHAREKVERGI { get; set; }
    }
}
