//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Olivetti
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ETA_DENEME_2016Entities : DbContext
    {
        public ETA_DENEME_2016Entities()
            : base("name=ETA_DENEME_2016Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<DEPSTKKART> DEPSTKKART { get; set; }
        public DbSet<FATFIS> FATFIS { get; set; }
        public DbSet<FATFISTIP> FATFISTIP { get; set; }
        public DbSet<FATFISTOPLAM> FATFISTOPLAM { get; set; }
        public DbSet<HARREFNO> HARREFNO { get; set; }
        public DbSet<SIRKETLOG> SIRKETLOG { get; set; }
        public DbSet<STKFIS> STKFIS { get; set; }
        public DbSet<STKFISTIP> STKFISTIP { get; set; }
        public DbSet<STKFIYAT> STKFIYAT { get; set; }
        public DbSet<STKFIYTIP> STKFIYTIP { get; set; }
        public DbSet<STKHAR> STKHAR { get; set; }
        public DbSet<STKKART> STKKART { get; set; }
        public DbSet<STKMIZDEGER> STKMIZDEGER { get; set; }
        public DbSet<FATHAR> FATHAR { get; set; }
        public DbSet<STKBARKOD> STKBARKOD { get; set; }
        public DbSet<STKBIRIM> STKBIRIM { get; set; }
        public DbSet<STKBOYFIYAT> STKBOYFIYAT { get; set; }
        public DbSet<STKBOYUT> STKBOYUT { get; set; }
        public DbSet<STKDETAY> STKDETAY { get; set; }
    }
}
