//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Olivetti
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class myEntities : DbContext
    {
        public myEntities()
            : base("name=myEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<DEPO> DEPO { get; set; }
        public DbSet<STKKART> STKKART { get; set; }
        public DbSet<CARHAR> CARHAR { get; set; }
        public DbSet<FATFIS> FATFIS { get; set; }
        public DbSet<FATFISTIP> FATFISTIP { get; set; }
        public DbSet<FATFISTOPLAM> FATFISTOPLAM { get; set; }
        public DbSet<FATHAR> FATHAR { get; set; }
        public DbSet<HARREFNO> HARREFNO { get; set; }
        public DbSet<SATFIS> SATFIS { get; set; }
        public DbSet<SATFISTIP> SATFISTIP { get; set; }
        public DbSet<SATFISTOPLAM> SATFISTOPLAM { get; set; }
        public DbSet<SATHAR> SATHAR { get; set; }
        public DbSet<SATKART> SATKART { get; set; }
        public DbSet<STKBARKOD> STKBARKOD { get; set; }
        public DbSet<STKBIRIM> STKBIRIM { get; set; }
        public DbSet<STKBOYFIYAT> STKBOYFIYAT { get; set; }
        public DbSet<STKFIS> STKFIS { get; set; }
        public DbSet<STKFISTIP> STKFISTIP { get; set; }
        public DbSet<STKFIYAT> STKFIYAT { get; set; }
        public DbSet<STKHAR> STKHAR { get; set; }
        public DbSet<STKMIZDEGER> STKMIZDEGER { get; set; }
    }
}
