//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Olivetti
{
    using System;
    using System.Collections.Generic;
    
    public partial class SATFIS
    {
        public System.DateTime SATFISTAR { get; set; }
        public int SATFISREFNO { get; set; }
        public int SATFISTIPI { get; set; }
        public int SATFISGCFLAG { get; set; }
        public int SATFISISTUR { get; set; }
        public int SATFISKAYONC { get; set; }
        public int SATFISKAYNAK { get; set; }
        public int SATFISTALREFNO { get; set; }
        public int SATFISTEKREFNO { get; set; }
        public int SATFISSONDURUM { get; set; }
        public System.DateTime SATFISSONDURTAR { get; set; }
        public string SATFISSONDURNOT { get; set; }
        public int SATFISBASFLAG { get; set; }
        public int SATFISKDVDAHILFLAG { get; set; }
        public System.DateTime SATFISBASTAR { get; set; }
        public string SATFISBASSAAT { get; set; }
        public System.DateTime SATFISBITTAR { get; set; }
        public string SATFISBITSAAT { get; set; }
        public System.DateTime SATFISVADETAR { get; set; }
        public string SATFISANADEPO { get; set; }
        public string SATFISPARTIKOD { get; set; }
        public string SATFISODEMEKOD { get; set; }
        public string SATFISSATKOD { get; set; }
        public string SATFISMASMER { get; set; }
        public int SATFISKARTTIP { get; set; }
        public string SATFISKARTKOD { get; set; }
        public string SATFISKARTUNVAN { get; set; }
        public string SATFISEVRAKNO1 { get; set; }
        public string SATFISEVRAKNO2 { get; set; }
        public string SATFISEVRAKNO3 { get; set; }
        public string SATFISOZKOD1 { get; set; }
        public string SATFISOZKOD2 { get; set; }
        public string SATFISOZKOD3 { get; set; }
        public string SATFISACIKLAMA1 { get; set; }
        public string SATFISACIKLAMA2 { get; set; }
        public string SATFISACIKLAMA3 { get; set; }
        public string SATFISHAZKOD { get; set; }
        public System.DateTime SATFISHAZTAR { get; set; }
        public string SATFISHAZNOT { get; set; }
        public string SATFISKONTKOD { get; set; }
        public System.DateTime SATFISKONTTAR { get; set; }
        public string SATFISKONTNOT { get; set; }
        public string SATFISONAYKOD { get; set; }
        public System.DateTime SATFISONAYTAR { get; set; }
        public string SATFISONAYNOT { get; set; }
        public decimal SATFISKDVORANI { get; set; }
        public System.DateTime SATFISKDVVADETAR { get; set; }
        public decimal SATFISMALTOP { get; set; }
        public decimal SATFISKALINDYTOP { get; set; }
        public decimal SATFISKALINDTTOP { get; set; }
        public decimal SATFISSATINDTOP { get; set; }
        public decimal SATFISGENINDTOP { get; set; }
        public decimal SATFISSATMASTOP { get; set; }
        public decimal SATFISGENMASTOP { get; set; }
        public decimal SATFISBRUTTOPLAM { get; set; }
        public decimal SATFISKDVMATRAHI { get; set; }
        public decimal SATFISKDVTUTARI { get; set; }
        public decimal SATFISARATOPLAM { get; set; }
        public decimal SATFISKDVALTIINDTOP { get; set; }
        public decimal SATFISKDVALTIEKTOP { get; set; }
        public decimal SATFISGENTOPLAM { get; set; }
        public System.DateTime SATFISDOVTAR { get; set; }
        public string SATFISDOVKOD { get; set; }
        public string SATFISDOVTUR { get; set; }
        public decimal SATFISDOVKUR { get; set; }
        public decimal SATFISGENDOVTOP { get; set; }
        public int SATFISSEVNO { get; set; }
        public string SATFISISYKOD { get; set; }
        public int SATFISOTVFLAG { get; set; }
        public int SATFISOTVKDVBLOKAJ { get; set; }
        public decimal SATFISTOPOTV { get; set; }
        public decimal SATFISTOPOTUT { get; set; }
        public int SATFISADRESNO { get; set; }
        public string SATFISADRES1 { get; set; }
        public string SATFISADRES2 { get; set; }
        public string SATFISADRES3 { get; set; }
        public string SATFISPOSTAKOD { get; set; }
        public string SATFISULKE { get; set; }
        public string SATFISIL { get; set; }
        public string SATFISILCE { get; set; }
        public string SATFISVERDAIRE { get; set; }
        public string SATFISVERHESNO { get; set; }
        public int SATFISKAPALIFLAG { get; set; }
        public string SATFISTCKIMLIKNO { get; set; }
        public int SATFISFATREFNO { get; set; }
        public System.DateTime SATFISFATTAR { get; set; }
        public int SATFISFATFLAG { get; set; }
        public int SATFISIRSREFNO { get; set; }
        public System.DateTime SATFISIRSTAR { get; set; }
        public int SATFISIRSFLAG { get; set; }
        public int SATFISSIPREFNO { get; set; }
        public System.DateTime SATFISSIPTAR { get; set; }
        public int SATFISSIPFLAG { get; set; }
        public System.DateTime SATFISTRNTAR { get; set; }
        public int SATFISTRNREFNO { get; set; }
        public int SATFISTRNTIPI { get; set; }
        public int SATFISEFATFLAG { get; set; }
        public decimal SATFISEKVERGIINDTOP { get; set; }
        public decimal SATFISEKVERGIILVTOP { get; set; }
        public decimal SATFISEKVERGITOP { get; set; }
    }
}
