//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Olivetti
{
    using System;
    using System.Collections.Generic;
    
    public partial class SATFISTIP
    {
        public int SATFTMODUL { get; set; }
        public int SATFTNO { get; set; }
        public string SATFTKOD { get; set; }
        public string SATFTACIKLAMA { get; set; }
        public int SATFTONAY { get; set; }
        public int SATFTEVRAKNO { get; set; }
        public string SATFTDIZDOS { get; set; }
        public int SATFTIRSFTNO { get; set; }
        public int SATFTFATFTNO { get; set; }
        public int SATFTSIPFTNO { get; set; }
        public int SATFTKDVDAHIL { get; set; }
        public int SATFTMAXSATIR { get; set; }
        public int SATFTOTVFLAG { get; set; }
        public int SATFTKDVOTVBLOKAJ { get; set; }
        public int SATFTKAPALI { get; set; }
        public int SATFTEEVRAKNO { get; set; }
    }
}
