//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Olivetti
{
    using System;
    using System.Collections.Generic;
    
    public partial class SATFISTOPLAM
    {
        public System.DateTime SATFTTAR { get; set; }
        public int SATFTREFNO { get; set; }
        public int SATFTTIPI { get; set; }
        public int SATFTGCFLAG { get; set; }
        public int SATFTKAYONC { get; set; }
        public int SATFTISTUR { get; set; }
        public int SATFTKAYNAK { get; set; }
        public int SATFTKDVDAHILFLAG { get; set; }
        public int SATFTKARTTIP { get; set; }
        public string SATFTKARTKOD { get; set; }
        public string SATFTEVRAKNO1 { get; set; }
        public string SATFTEVRAKNO2 { get; set; }
        public string SATFTEVRAKNO3 { get; set; }
        public int SATFTKONU { get; set; }
        public string SATFTBASLIK { get; set; }
        public decimal SATFTTUTAR { get; set; }
        public int SATFTONCELIK { get; set; }
        public string SATFTFORMUL { get; set; }
        public decimal SATFTMATRAH { get; set; }
        public decimal SATFTORAN { get; set; }
        public decimal SATFTKDVORAN { get; set; }
        public string SATFTDOVKOD { get; set; }
        public string SATFTDOVTUR { get; set; }
        public decimal SATFTDOVTUTAR { get; set; }
        public System.DateTime SATFTVADETAR { get; set; }
        public int SATFTTAMSAYI1 { get; set; }
        public int SATFTTAMSAYI2 { get; set; }
        public int SATFTTAMSAYI3 { get; set; }
        public string SATFTKOSUL { get; set; }
        public string SATFTACIKLAMA1 { get; set; }
        public decimal SATFTSAYI1 { get; set; }
        public int SATFTVADESAYI { get; set; }
        public string SATFTTAHKARTKOD { get; set; }
        public int SATFTEFATFLAG { get; set; }
    }
}
