//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Olivetti
{
    using System;
    using System.Collections.Generic;
    
    public partial class SATHAR
    {
        public System.DateTime SATHARTAR { get; set; }
        public int SATHARREFNO { get; set; }
        public int SATHARTIPI { get; set; }
        public int SATHARGCFLAG { get; set; }
        public int SATHARISTUR { get; set; }
        public int SATHARKAYONC { get; set; }
        public int SATHARKAYNAK { get; set; }
        public string SATHARKARTKOD { get; set; }
        public string SATHAREVRAKNO { get; set; }
        public int SATHARSIRANO { get; set; }
        public int SATHARKODTIP { get; set; }
        public string SATHARSTKKOD { get; set; }
        public string SATHARSTKCINS { get; set; }
        public string SATHARSTKBRM { get; set; }
        public string SATHARDEPOKOD { get; set; }
        public string SATHARBARKOD { get; set; }
        public string SATHAROZDESKOD { get; set; }
        public string SATHARBENZERKOD { get; set; }
        public decimal SATHARMIKTAR { get; set; }
        public decimal SATHARMIKTAR2 { get; set; }
        public decimal SATHARMIKTAR3 { get; set; }
        public decimal SATHARMIKTAR4 { get; set; }
        public decimal SATHARMIKTAR5 { get; set; }
        public string SATHARFIYTIP { get; set; }
        public decimal SATHARFIYAT { get; set; }
        public decimal SATHARTUTAR { get; set; }
        public string SATHARDOVKOD { get; set; }
        public string SATHARDOVTUR { get; set; }
        public decimal SATHARDOVTUTAR { get; set; }
        public string SATHAROZKOD { get; set; }
        public string SATHARACIKLAMA { get; set; }
        public decimal SATHARKDVYUZ { get; set; }
        public decimal SATHARISKYUZ1 { get; set; }
        public decimal SATHARISKYUZ2 { get; set; }
        public decimal SATHARISKYUZ3 { get; set; }
        public decimal SATHARISKYUZ4 { get; set; }
        public decimal SATHARISKYUZ5 { get; set; }
        public decimal SATHARISKYTUT1 { get; set; }
        public decimal SATHARISKYTUT2 { get; set; }
        public decimal SATHARISKYTUT3 { get; set; }
        public decimal SATHARISKYTUT4 { get; set; }
        public decimal SATHARISKYTUT5 { get; set; }
        public decimal SATHARISKGTUT1 { get; set; }
        public decimal SATHARISKGTUT2 { get; set; }
        public decimal SATHARISKGTUT3 { get; set; }
        public decimal SATHARISKGTUT4 { get; set; }
        public decimal SATHARISKGTUT5 { get; set; }
        public decimal SATHARDIGERIND { get; set; }
        public decimal SATHARTOPLAMIND { get; set; }
        public decimal SATHARKDVMATRAH { get; set; }
        public decimal SATHARKDVTUTAR { get; set; }
        public decimal SATHARTOPLAMTUT { get; set; }
        public System.DateTime SATHARVADETAR { get; set; }
        public string SATHARACIKLAMA1 { get; set; }
        public string SATHARACIKLAMA2 { get; set; }
        public string SATHARACIKLAMA3 { get; set; }
        public string SATHARPARTINO { get; set; }
        public string SATHARMASMER { get; set; }
        public string SATHARSERINO1 { get; set; }
        public string SATHARSERINO2 { get; set; }
        public int SATHARRB1 { get; set; }
        public int SATHARRB2 { get; set; }
        public int SATHARRB3 { get; set; }
        public int SATHARRB4 { get; set; }
        public int SATHARRB5 { get; set; }
        public string SATHARSATKOD { get; set; }
        public string SATHARODEMEKOD { get; set; }
        public decimal SATHARTOPLAMMAS { get; set; }
        public decimal SATHARNETTUTAR { get; set; }
        public decimal SATHARNETFIYAT { get; set; }
        public decimal SATHARMALIYET { get; set; }
        public int SATHARKARTTIP { get; set; }
        public System.DateTime SATHARBASTAR { get; set; }
        public string SATHARBASSAAT { get; set; }
        public System.DateTime SATHARBITTAR { get; set; }
        public string SATHARBITSAAT { get; set; }
        public decimal SATHAROTVMATRAH { get; set; }
        public decimal SATHAROTVORAN { get; set; }
        public decimal SATHAROTVFIYAT { get; set; }
        public decimal SATHARTOPOTV { get; set; }
        public decimal SATHAROTVTUTAR { get; set; }
        public decimal SATHARDOVFIYAT { get; set; }
        public decimal SATHAREBTEN { get; set; }
        public decimal SATHAREBTBOY { get; set; }
        public decimal SATHAREBTYUK { get; set; }
        public decimal SATHAREBTHCM { get; set; }
        public decimal SATHAREBTAGR { get; set; }
        public string SATHAREKCHAR1 { get; set; }
        public string SATHAREKCHAR2 { get; set; }
        public int SATHAREKINT1 { get; set; }
        public int SATHAREKINT2 { get; set; }
        public System.DateTime SATHAREKDATE1 { get; set; }
        public System.DateTime SATHAREKDATE2 { get; set; }
        public decimal SATHAREKTUT1 { get; set; }
        public decimal SATHAREKTUT2 { get; set; }
        public decimal SATHAREKMIK1 { get; set; }
        public decimal SATHAREKMIK2 { get; set; }
        public decimal SATHAREKDOVTUT1 { get; set; }
        public decimal SATHAREKDOVTUT2 { get; set; }
        public decimal SATHAREKORAN1 { get; set; }
        public decimal SATHAREKORAN2 { get; set; }
        public decimal SATHARDOVKUR { get; set; }
        public int SATHAREFATFLAG { get; set; }
        public string SATHAROTVVERKOD { get; set; }
        public string SATHAREKVERGI { get; set; }
    }
}
