//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Olivetti
{
    using System;
    using System.Collections.Generic;
    
    public partial class SATKART
    {
        public string SATKOD { get; set; }
        public string SATUNVAN { get; set; }
        public string SATUNVAN2 { get; set; }
        public string SATUNVAN3 { get; set; }
        public string SATYETKILI { get; set; }
        public string SATYETKILI2 { get; set; }
        public string SATYETKILI3 { get; set; }
        public string SATOZKOD1 { get; set; }
        public string SATOZKOD2 { get; set; }
        public string SATOZKOD3 { get; set; }
        public string SATOZKOD4 { get; set; }
        public string SATOZKOD5 { get; set; }
        public string SATDOVKOD1 { get; set; }
        public string SATDOVTUR1 { get; set; }
        public string SATDOVKOD2 { get; set; }
        public string SATDOVTUR2 { get; set; }
        public string SATDOVKOD3 { get; set; }
        public string SATDOVTUR3 { get; set; }
        public string SATDOVKOD4 { get; set; }
        public string SATDOVTUR4 { get; set; }
        public string SATDOVKOD5 { get; set; }
        public string SATDOVTUR5 { get; set; }
        public string SATVERDAIRE { get; set; }
        public string SATVERHESNO { get; set; }
        public string SATOZELKARTNO { get; set; }
        public string SATODASICILNO { get; set; }
        public string SATACIK1 { get; set; }
        public string SATACIK2 { get; set; }
        public string SATACIK3 { get; set; }
        public string SATACIK4 { get; set; }
        public string SATACIK5 { get; set; }
        public int SATCALFLAG { get; set; }
        public string SATDERECE { get; set; }
        public string SATUYARI { get; set; }
        public decimal SATISKYUZ { get; set; }
        public int SATMUAFGUN { get; set; }
        public string SATTAHSILKOD { get; set; }
        public string SATTAHSILACK { get; set; }
        public decimal SATKREDILIMIT { get; set; }
        public decimal SATRISKLIMIT { get; set; }
        public decimal SATSIPALIMLIMIT { get; set; }
        public decimal SATSIPSATIMLIMIT { get; set; }
        public int SATHESAPGUN { get; set; }
        public string SATVADENO { get; set; }
        public string SATODEPLANGRUPNO { get; set; }
        public string SATTAKSITGRUPNO { get; set; }
        public System.DateTime SATMUTABAKATTAR { get; set; }
        public decimal SATMUTABAKATTUT { get; set; }
        public string SATGRUPKODU { get; set; }
        public string SATSEKTORKODU { get; set; }
        public string SATBOLGEKODU { get; set; }
        public string SATSTKALISFIYNO { get; set; }
        public string SATSTKSATISFIYNO { get; set; }
        public string SATLISFIYNO { get; set; }
        public string SATKEFILKODU1 { get; set; }
        public string SATKEFILKODU2 { get; set; }
        public string SATKEFILKODU3 { get; set; }
        public string SATKEFILKODU4 { get; set; }
        public string SATKEFILKODU5 { get; set; }
        public int SATMUHTIPI { get; set; }
        public string SATMUHKODU { get; set; }
        public int SATYAZADRNO { get; set; }
        public int SATFATADRNO { get; set; }
        public int SATIRSADRNO { get; set; }
        public decimal SATBORCTOP { get; set; }
        public decimal SATALACAKTOP { get; set; }
        public decimal SATBAKIYE { get; set; }
        public string SATKREDIDOVKOD { get; set; }
        public string SATKREDIDOVTUR { get; set; }
        public string SATRISKDOVKOD { get; set; }
        public string SATRISKDOVTUR { get; set; }
        public decimal SATTEMINATTUT { get; set; }
        public string SATTEMDOVKOD { get; set; }
        public string SATTEMDOVTUR { get; set; }
        public string SATGRUPKOD { get; set; }
        public int SATKARALISTEFLAG { get; set; }
        public string SATKARALISTEACK { get; set; }
        public int SATSEVNO { get; set; }
        public decimal SATGIRIRSTOP { get; set; }
        public decimal SATCIKIRSTOP { get; set; }
        public decimal SATGIRSIPTOPTUT { get; set; }
        public decimal SATCIKSIPTOPTUT { get; set; }
        public int SATGIRSIPTUTFLAG { get; set; }
        public decimal SATGIRSIPMINTUT { get; set; }
        public decimal SATGIRSIPMAXTUT { get; set; }
        public int SATCIKSIPTUTFLAG { get; set; }
        public decimal SATCIKSIPMINTUT { get; set; }
        public decimal SATCIKSIPMAXTUT { get; set; }
        public decimal SATOZELBORCTOP { get; set; }
        public decimal SATOZELALACAKTOP { get; set; }
        public decimal SATOZELBAKIYE { get; set; }
        public string SATEKCHAR1 { get; set; }
        public string SATEKCHAR2 { get; set; }
        public int SATEKINT1 { get; set; }
        public int SATEKINT2 { get; set; }
        public System.DateTime SATEKDATE1 { get; set; }
        public System.DateTime SATEKDATE2 { get; set; }
        public decimal SATEKDBL1 { get; set; }
        public decimal SATEKDBL2 { get; set; }
    }
}
