//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Olivetti
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIRKETLOG
    {
        public int SIRLOGMODUL { get; set; }
        public int SIRLOGKONU { get; set; }
        public int SIRLOGKYTTIPI { get; set; }
        public string SIRLOGKYTKODU { get; set; }
        public string SIRLOGKYTKODU2 { get; set; }
        public int SIRLOGKYTREFNO { get; set; }
        public int SIRLOGKYTREFNO2 { get; set; }
        public string SIRLOGILKKULKOD { get; set; }
        public System.DateTime SIRLOGILKTAR { get; set; }
        public string SIRLOGSONKULKOD { get; set; }
        public System.DateTime SIRLOGSONTAR { get; set; }
        public int SIRLOGMUHINT1 { get; set; }
        public int SIRLOGMUHINT2 { get; set; }
        public int SIRLOGMUHINT3 { get; set; }
        public int SIRLOGMUHINT4 { get; set; }
        public int SIRLOGMUHINT5 { get; set; }
        public decimal SIRLOGMUHNUM1 { get; set; }
        public decimal SIRLOGMUHNUM2 { get; set; }
        public decimal SIRLOGMUHNUM3 { get; set; }
        public decimal SIRLOGMUHNUM4 { get; set; }
        public decimal SIRLOGMUHNUM5 { get; set; }
        public System.DateTime SIRLOGMUHTAR1 { get; set; }
        public System.DateTime SIRLOGMUHTAR2 { get; set; }
        public System.DateTime SIRLOGMUHTAR3 { get; set; }
        public System.DateTime SIRLOGMUHTAR4 { get; set; }
        public System.DateTime SIRLOGMUHTAR5 { get; set; }
        public string SIRLOGMUHACK1 { get; set; }
        public string SIRLOGMUHACK2 { get; set; }
        public string SIRLOGMUHACK3 { get; set; }
        public string SIRLOGMUHACK4 { get; set; }
        public string SIRLOGMUHACK5 { get; set; }
    }
}
