//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Olivetti
{
    using System;
    using System.Collections.Generic;
    
    public partial class STKBOYUT
    {
        public string STKBOYSTOKKOD { get; set; }
        public string STKBOYDEPOKOD { get; set; }
        public int STKBOYBOYUT1 { get; set; }
        public int STKBOYBOYUT2 { get; set; }
        public int STKBOYBOYUT3 { get; set; }
        public int STKBOYBOYUT4 { get; set; }
        public int STKBOYBOYUT5 { get; set; }
        public decimal STKBOYDEVIR { get; set; }
        public decimal STKBOYGIREN { get; set; }
        public decimal STKBOYCIKAN { get; set; }
        public decimal STKBOYBAKIYE { get; set; }
        public string STKBOYACIKLAMA { get; set; }
        public string STKBOYOZELKOD { get; set; }
        public decimal STKBOYGIRSIPMIK { get; set; }
        public decimal STKBOYCIKSIPMIK { get; set; }
        public decimal STKBOYGIRURTMIK { get; set; }
        public decimal STKBOYCIKURTMIK { get; set; }
    }
}
