//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Olivetti
{
    using System;
    using System.Collections.Generic;
    
    public partial class STKBARKOD
    {
        public string STKBARKOD1 { get; set; }
        public string STKBARSTKKOD { get; set; }
        public int STKBARBRMNO { get; set; }
        public decimal STKBARKATSAYI { get; set; }
        public int STKBARTIP { get; set; }
        public int STKBARYAPINO { get; set; }
        public int STKBARBOYUT1 { get; set; }
        public int STKBARBOYUT2 { get; set; }
        public int STKBARBOYUT3 { get; set; }
        public int STKBARBOYUT4 { get; set; }
        public int STKBARBOYUT5 { get; set; }
        public string STKBARFIYTIP { get; set; }
        public int STKBARITEMNO { get; set; }
    }
}
