//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Olivetti
{
    using System;
    using System.Collections.Generic;
    
    public partial class STKBOYFIYAT
    {
        public string STKBOYFIYSTKKOD { get; set; }
        public string STKBOYFIYDEPKOD { get; set; }
        public int STKBOYFIYBOYUT1 { get; set; }
        public int STKBOYFIYBOYUT2 { get; set; }
        public int STKBOYFIYBOYUT3 { get; set; }
        public int STKBOYFIYBOYUT4 { get; set; }
        public int STKBOYFIYBOYUT5 { get; set; }
        public int STKBOYFIYNO { get; set; }
        public decimal STKBOYFIYTUTAR { get; set; }
    }
}
