//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Olivetti
{
    using System;
    using System.Collections.Generic;
    
    public partial class STKDETAY
    {
        public string STKDETBKOD { get; set; }
        public string STKDETSKOD { get; set; }
        public int STKDETTIP { get; set; }
        public int STKDETITEMNO { get; set; }
    }
}
