//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Olivetti
{
    using System;
    using System.Collections.Generic;
    
    public partial class STKFIYTIP
    {
        public int STKFTFIYNO { get; set; }
        public string STKFTFIYADI { get; set; }
        public string STKFTFIYACK { get; set; }
        public int STKFTFIYTIPI { get; set; }
        public string STKFTFIYDOVKOD { get; set; }
        public string STKFTFIYDOVTUR { get; set; }
        public decimal STKFTFIYISKYUZ1 { get; set; }
        public decimal STKFTFIYISKYUZ2 { get; set; }
        public decimal STKFTFIYISKYUZ3 { get; set; }
        public decimal STKFTFIYISKYUZ4 { get; set; }
        public decimal STKFTFIYISKYUZ5 { get; set; }
        public int STKFTFIYKDVNO { get; set; }
        public int STKFTFIYKDVFLAG { get; set; }
        public int STKFTFIYODEGUN { get; set; }
        public System.DateTime STKFTFIYBASTAR { get; set; }
        public string STKFTFIYBASSAAT { get; set; }
        public System.DateTime STKFTFIYBITTAR { get; set; }
        public string STKFTFIYBITSAAT { get; set; }
        public int STKFTFIYKONTFLAG { get; set; }
        public int STKFTFIYDEPO { get; set; }
        public int STKFTFIYKULFLAG { get; set; }
    }
}
