//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Olivetti
{
    using System;
    using System.Collections.Generic;
    
    public partial class STKFIS
    {
        public System.DateTime STKFISTAR { get; set; }
        public int STKFISREFNO { get; set; }
        public int STKFISTIPI { get; set; }
        public int STKFISGCFLAG { get; set; }
        public int STKFISKAYONC { get; set; }
        public int STKFISDEPO { get; set; }
        public int STKFISOZELFIS { get; set; }
        public int STKFISIADE { get; set; }
        public int STKFISKAYNAK { get; set; }
        public string STKFISCARKOD { get; set; }
        public int STKFISREFNO2 { get; set; }
        public string STKFISANADEPO { get; set; }
        public string STKFISKARDEPO { get; set; }
        public string STKFISOZKOD1 { get; set; }
        public string STKFISOZKOD2 { get; set; }
        public string STKFISOZKOD3 { get; set; }
        public string STKFISACIKLAMA1 { get; set; }
        public string STKFISACIKLAMA2 { get; set; }
        public string STKFISACIKLAMA3 { get; set; }
        public string STKFISEVRAKNO1 { get; set; }
        public string STKFISEVRAKNO2 { get; set; }
        public string STKFISEVRAKNO3 { get; set; }
        public System.DateTime STKFISDOVTAR { get; set; }
        public string STKFISPARTIKOD { get; set; }
        public string STKFISMASMER { get; set; }
        public decimal STKFISTOPBTUT { get; set; }
        public decimal STKFISTOPISK { get; set; }
        public decimal STKFISTOPNTUT { get; set; }
        public decimal STKFISTOPKDV { get; set; }
        public decimal STKFISTOPKTUT { get; set; }
        public int STKFISSEVNO { get; set; }
        public string STKFISISYKOD { get; set; }
        public int STKFISOTVFLAG { get; set; }
        public decimal STKFISTOPOTV { get; set; }
        public decimal STKFISTOPOTUT { get; set; }
        public string STKFISDOVKOD { get; set; }
        public string STKFISDOVTUR { get; set; }
        public decimal STKFISDOVKUR { get; set; }
        public decimal STKFISDOVTOP { get; set; }
        public System.DateTime STKFISTRNTAR { get; set; }
        public int STKFISTRNREFNO { get; set; }
        public int STKFISTRNTIPI { get; set; }
    }
}
