//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Olivetti
{
    using System;
    using System.Collections.Generic;
    
    public partial class STKFISTIP
    {
        public int STKFTMODUL { get; set; }
        public int STKFTNO { get; set; }
        public string STKFTKOD { get; set; }
        public string STKFTACIKLAMA { get; set; }
        public int STKFTONAY { get; set; }
        public int STKFTEVRAKNO { get; set; }
        public string STKFTDIZDOS { get; set; }
        public string STKFTFIYTIP { get; set; }
        public int STKFTMAXSATIR { get; set; }
        public int STKFTOTVFLAG { get; set; }
    }
}
