//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Olivetti
{
    using System;
    using System.Collections.Generic;
    
    public partial class STKFIYAT
    {
        public string STKFIYSTKKOD { get; set; }
        public string STKFIYDEPKOD { get; set; }
        public int STKFIYNO { get; set; }
        public int STKFIYITEMNO { get; set; }
        public decimal STKFIYTUTAR { get; set; }
        public string STKFIYDOVKOD { get; set; }
        public string STKFIYDOVTUR { get; set; }
        public decimal STKFIYISKYUZ1 { get; set; }
        public decimal STKFIYISKYUZ2 { get; set; }
        public decimal STKFIYISKYUZ3 { get; set; }
        public decimal STKFIYISKYUZ4 { get; set; }
        public decimal STKFIYISKYUZ5 { get; set; }
        public decimal STKFIYISKTUT1 { get; set; }
        public decimal STKFIYISKTUT2 { get; set; }
        public decimal STKFIYISKTUT3 { get; set; }
        public decimal STKFIYISKTUT4 { get; set; }
        public decimal STKFIYISKTUT5 { get; set; }
        public int STKFIYKDVNO { get; set; }
        public int STKFIYKDVFLAG { get; set; }
        public int STKFIYODEGUN { get; set; }
        public System.DateTime STKFIYBASTAR { get; set; }
        public string STKFIYBASSAAT { get; set; }
        public System.DateTime STKFIYBITTAR { get; set; }
        public string STKFIYBITSAAT { get; set; }
        public int STKFIYKONTFLAG { get; set; }
        public string STKFIYODEKOD { get; set; }
    }
}
