//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Olivetti
{
    using System;
    using System.Collections.Generic;
    
    public partial class STKHAR
    {
        public System.DateTime STKHARTAR { get; set; }
        public int STKHARREFNO { get; set; }
        public int STKHARTIPI { get; set; }
        public int STKHARGCFLAG { get; set; }
        public int STKHARKAYONC { get; set; }
        public int STKHARDEPO { get; set; }
        public int STKHAROZELFIS { get; set; }
        public int STKHARIADE { get; set; }
        public int STKHARKAYNAK { get; set; }
        public string STKHARCARKOD { get; set; }
        public int STKHARREFNO2 { get; set; }
        public string STKHARANADEPO { get; set; }
        public string STKHARKARDEPO { get; set; }
        public string STKHARSTKKOD { get; set; }
        public string STKHARSTKCINS { get; set; }
        public string STKHARSTKBRM { get; set; }
        public string STKHARBARKOD { get; set; }
        public string STKHAROZDESKOD { get; set; }
        public string STKHARBENZERKOD { get; set; }
        public decimal STKHARMIKTAR { get; set; }
        public decimal STKHARMIKTAR2 { get; set; }
        public decimal STKHARMIKTAR3 { get; set; }
        public decimal STKHARMIKTAR4 { get; set; }
        public decimal STKHARMIKTAR5 { get; set; }
        public decimal STKHARFIYAT { get; set; }
        public decimal STKHARTUTAR { get; set; }
        public string STKHARDOVKOD { get; set; }
        public string STKHARDOVTUR { get; set; }
        public decimal STKHARDOVTUTAR { get; set; }
        public string STKHAROZKOD { get; set; }
        public string STKHARACIKLAMA { get; set; }
        public decimal STKHARKDVYUZ { get; set; }
        public decimal STKHARISKYUZ1 { get; set; }
        public decimal STKHARISKYUZ2 { get; set; }
        public decimal STKHARISKYUZ3 { get; set; }
        public decimal STKHARISKYUZ4 { get; set; }
        public decimal STKHARISKYUZ5 { get; set; }
        public decimal STKHARISKYTUT1 { get; set; }
        public decimal STKHARISKYTUT2 { get; set; }
        public decimal STKHARISKYTUT3 { get; set; }
        public decimal STKHARISKYTUT4 { get; set; }
        public decimal STKHARISKYTUT5 { get; set; }
        public decimal STKHARISKGTUT1 { get; set; }
        public decimal STKHARISKGTUT2 { get; set; }
        public decimal STKHARISKGTUT3 { get; set; }
        public decimal STKHARISKGTUT4 { get; set; }
        public decimal STKHARISKGTUT5 { get; set; }
        public decimal STKHARDIGERIND { get; set; }
        public decimal STKHARTOPLAMIND { get; set; }
        public decimal STKHARKDVMATRAH { get; set; }
        public decimal STKHARKDVTUTAR { get; set; }
        public decimal STKHARTOPLAMTUT { get; set; }
        public System.DateTime STKHARVADETAR { get; set; }
        public string STKHARACIKLAMA1 { get; set; }
        public string STKHARACIKLAMA2 { get; set; }
        public string STKHARACIKLAMA3 { get; set; }
        public string STKHARPARTINO { get; set; }
        public string STKHARMASMER { get; set; }
        public string STKHARSERINO1 { get; set; }
        public string STKHARSERINO2 { get; set; }
        public int STKHARRB1 { get; set; }
        public int STKHARRB2 { get; set; }
        public int STKHARRB3 { get; set; }
        public int STKHARRB4 { get; set; }
        public int STKHARRB5 { get; set; }
        public string STKHARFIYTIP { get; set; }
        public int STKHARSIRANO { get; set; }
        public decimal STKHARTOPLAMMAS { get; set; }
        public decimal STKHARNETTUTAR { get; set; }
        public decimal STKHARNETFIYAT { get; set; }
        public decimal STKHARMALIYET { get; set; }
        public decimal STKHAROTVMATRAH { get; set; }
        public decimal STKHAROTVORAN { get; set; }
        public decimal STKHAROTVFIYAT { get; set; }
        public decimal STKHARTOPOTV { get; set; }
        public decimal STKHAROTVTUTAR { get; set; }
        public decimal STKHARDOVFIYAT { get; set; }
        public decimal STKHAREBTEN { get; set; }
        public decimal STKHAREBTBOY { get; set; }
        public decimal STKHAREBTYUK { get; set; }
        public decimal STKHAREBTHCM { get; set; }
        public decimal STKHAREBTAGR { get; set; }
        public string STKHAREKCHAR1 { get; set; }
        public string STKHAREKCHAR2 { get; set; }
        public int STKHAREKINT1 { get; set; }
        public int STKHAREKINT2 { get; set; }
        public System.DateTime STKHAREKDATE1 { get; set; }
        public System.DateTime STKHAREKDATE2 { get; set; }
        public decimal STKHAREKTUT1 { get; set; }
        public decimal STKHAREKTUT2 { get; set; }
        public decimal STKHAREKMIK1 { get; set; }
        public decimal STKHAREKMIK2 { get; set; }
        public decimal STKHAREKDOVTUT1 { get; set; }
        public decimal STKHAREKDOVTUT2 { get; set; }
        public decimal STKHAREKORAN1 { get; set; }
        public decimal STKHAREKORAN2 { get; set; }
        public decimal STKHARDOVKUR { get; set; }
    }
}
