//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Olivetti
{
    using System;
    using System.Collections.Generic;
    
    public partial class STKKART
    {
        public string STKKOD { get; set; }
        public string STKCINSI { get; set; }
        public string STKCINSI2 { get; set; }
        public string STKCINSI3 { get; set; }
        public string STKBIRIM { get; set; }
        public string STKBIRIM2 { get; set; }
        public decimal STKBRM2CAR { get; set; }
        public decimal STKBRM2BOL { get; set; }
        public string STKBIRIM3 { get; set; }
        public decimal STKBRM3CAR { get; set; }
        public decimal STKBRM3BOL { get; set; }
        public string STKBIRIM4 { get; set; }
        public decimal STKBRM4CAR { get; set; }
        public decimal STKBRM4BOL { get; set; }
        public string STKBIRIM5 { get; set; }
        public decimal STKBRM5CAR { get; set; }
        public decimal STKBRM5BOL { get; set; }
        public string STKOZKOD1 { get; set; }
        public string STKOZKOD2 { get; set; }
        public string STKOZKOD3 { get; set; }
        public string STKOZKOD4 { get; set; }
        public string STKOZKOD5 { get; set; }
        public int STKKARTTIP1 { get; set; }
        public int STKKARTTIP2 { get; set; }
        public int STKKARTTIP3 { get; set; }
        public int STKKARTTIP4 { get; set; }
        public int STKKARTTIP5 { get; set; }
        public int STKKARTTIP6 { get; set; }
        public int STKKARTTIP7 { get; set; }
        public int STKKARTTIP8 { get; set; }
        public int STKKARTTIP9 { get; set; }
        public int STKKARTTIP10 { get; set; }
        public int STKKARTTIP11 { get; set; }
        public int STKKARTTIP12 { get; set; }
        public int STKKARTTIP13 { get; set; }
        public int STKKARTTIP14 { get; set; }
        public decimal STKBAKIYE { get; set; }
        public decimal STKBAKIYE2 { get; set; }
        public decimal STKBAKIYE3 { get; set; }
        public decimal STKBAKIYE4 { get; set; }
        public decimal STKBAKIYE5 { get; set; }
        public decimal STKYAOFIYAT { get; set; }
        public string STKACIK1 { get; set; }
        public string STKACIK2 { get; set; }
        public string STKACIK3 { get; set; }
        public string STKACIK4 { get; set; }
        public string STKACIK5 { get; set; }
        public int STKGENKDVNO { get; set; }
        public decimal STKGENISK1 { get; set; }
        public decimal STKGENISK2 { get; set; }
        public decimal STKGENISK3 { get; set; }
        public decimal STKGENISK4 { get; set; }
        public decimal STKGENISK5 { get; set; }
        public decimal STKKRITIKSEVIYE { get; set; }
        public decimal STKOPTIMALSEVIYE { get; set; }
        public int STKODEGUN { get; set; }
        public string STKPROKOD { get; set; }
        public System.DateTime STKSYFTARIHI { get; set; }
        public string STKSYFSAATI { get; set; }
        public int STKBOZULMASURESI { get; set; }
        public int STKKULLANIMSURESI { get; set; }
        public decimal STKEKSAHA1 { get; set; }
        public decimal STKEKSAHA2 { get; set; }
        public decimal STKEUAFIYAT { get; set; }
        public decimal STKEPAFIYAT { get; set; }
        public decimal STKEUSFIYAT { get; set; }
        public decimal STKEPSFIYAT { get; set; }
        public string STKURTSNKOD { get; set; }
        public int STKURTBRTIP { get; set; }
        public string STKBOLKODU { get; set; }
        public string STKREYKODU { get; set; }
        public string STKRAFKODU { get; set; }
        public int STKCALFLAG { get; set; }
        public int STKINDKONT { get; set; }
        public int STKFIYDEGALFLAG { get; set; }
        public int STKFIYDEGSATFLAG { get; set; }
        public int STKIADEALFLAG { get; set; }
        public int STKIADESATFLAG { get; set; }
        public int STKMIKKONTALFLAG { get; set; }
        public decimal STKMIKKONTALMIN { get; set; }
        public decimal STKMIKKONTALMAX { get; set; }
        public int STKMIKKONTSATFLAG { get; set; }
        public decimal STKMIKKONTSATMIN { get; set; }
        public decimal STKMIKKONTSATMAX { get; set; }
        public int STKFIYKONTALFLAG { get; set; }
        public decimal STKFIYKONTALMIN { get; set; }
        public decimal STKFIYKONTALMAX { get; set; }
        public int STKFIYKONTSATFLAG { get; set; }
        public decimal STKFIYKONTSATMIN { get; set; }
        public decimal STKFIYKONTSATMAX { get; set; }
        public string STKOTOGIRFIY { get; set; }
        public string STKOTOCIKFIY { get; set; }
        public string STKDOVKOD1 { get; set; }
        public string STKDOVTUR1 { get; set; }
        public string STKDOVKOD2 { get; set; }
        public string STKDOVTUR2 { get; set; }
        public string STKDOVKOD3 { get; set; }
        public string STKDOVTUR3 { get; set; }
        public string STKDOVKOD4 { get; set; }
        public string STKDOVTUR4 { get; set; }
        public string STKDOVKOD5 { get; set; }
        public string STKDOVTUR5 { get; set; }
        public string STKURUNSOR { get; set; }
        public string STKURETKOD { get; set; }
        public string STKURETADI { get; set; }
        public string STKTEDARIKKOD { get; set; }
        public string STKTEDARIKADI { get; set; }
        public string STKKALKONTKOD { get; set; }
        public int STKSN1EVRAKNO { get; set; }
        public int STKSN2EVRAKNO { get; set; }
        public string STKGRUPKOD { get; set; }
        public int STKSEVNO { get; set; }
        public decimal STKOZELBAKIYE { get; set; }
        public decimal STKOZELBAKIYE2 { get; set; }
        public decimal STKOZELBAKIYE3 { get; set; }
        public decimal STKOZELBAKIYE4 { get; set; }
        public decimal STKOZELBAKIYE5 { get; set; }
        public decimal STKREZGIRSIPMIK { get; set; }
        public decimal STKREZGIRSIPTUT { get; set; }
        public decimal STKREZCIKSIPMIK { get; set; }
        public decimal STKREZCIKSIPTUT { get; set; }
        public decimal STKREZGIRURTMIK { get; set; }
        public decimal STKREZGIRURTTUT { get; set; }
        public decimal STKREZCIKURTMIK { get; set; }
        public decimal STKREZCIKURTTUT { get; set; }
        public decimal STKOTVORAN { get; set; }
        public decimal STKOTVTUTAR { get; set; }
        public decimal STKFIREORAN { get; set; }
        public decimal STKKARORAN { get; set; }
        public int STKPARTIEVRAKNO { get; set; }
        public string STKOTVVERGIKOD { get; set; }
        public string STKEKVERGIKOD { get; set; }
        public string STKURESTKKOD { get; set; }
        public string STKTEDSTKKOD { get; set; }
        public string STKEKCHAR1 { get; set; }
        public string STKEKCHAR2 { get; set; }
        public int STKEKINT1 { get; set; }
        public int STKEKINT2 { get; set; }
        public System.DateTime STKEKDATE1 { get; set; }
        public System.DateTime STKEKDATE2 { get; set; }
        public decimal STKEKDBL1 { get; set; }
        public decimal STKEKDBL2 { get; set; }
    }
}
