//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Olivetti
{
    using System;
    using System.Collections.Generic;
    
    public partial class STKMIZDEGER
    {
        public string STKKOD { get; set; }
        public int STKYIL { get; set; }
        public int STKAY { get; set; }
        public int STKRAKTIP { get; set; }
        public string STKDOVKOD { get; set; }
        public decimal STKBORC { get; set; }
        public decimal STKALACAK { get; set; }
        public string STKDEPO { get; set; }
    }
}
